# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: Import Secrets
      uses: hashicorp/vault-action@v2
      with:
        url: http://127.0.0.1:8200
        token: ${{ secrets.VAULT_TOKEN }}
        secrets: |
          secret/docker DOCKERHUB_USERNAME
          secret/docker DOCKERHUB_TOKEN
        
    - name: Build JAR file
      run: mvn -B package --file pom.xml 
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}
        
    - name: Push to dockerhub 
      run: |
       docker build -t ${{ env.DOCKERHUB_USERNAME }}/first_image:latest .
       docker push ${{ env.DOCKERHUB_USERNAME }}/first_image

